### ISSUE TITLE
Insert 'Add event image' file 

### ISSUE THREAD

**Issue by JonesOnGit** [andygimma/invtr#23]
![add event image](https://cloud.githubusercontent.com/assets/14132693/14727918/d97f442a-07fd-11e6-9b5c-eb7ee8d9fe65.png)

**Comment by jcdavison** [comment]
https://www.dropbox.com/s/sji6die10q30uk2/Screenshot%202016-04-25%2015.57.29.png?dl=0

**Comment by jcdavison** [comment]
![screenshot 2016-04-25 15 57 29](https://cloud.githubusercontent.com/assets/6944945/14801507/7c090de0-0afe-11e6-82d2-f706e1110ee3.png)

**Comment by JonesOnGit** [comment]
It looks great thank you! But it's not working on mobile? The old image is
still there..?

On Mon, Apr 25, 2016 at 6:57 PM, John Davison <notifications@github.com>
wrote:

>
> https://www.dropbox.com/s/sji6die10q30uk2/Screenshot%202016-04-25%2015.57.29.png?dl=0
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/andygimma/invtr/issues/23#issuecomment-214556143>
>



-- 

Jessica Jones
Founder /
herenow.nyc <http://www.herenow.nyc>
